services:
  nats-server:
    image: nats:latest
    ports:
      - 4222:4222

  # authentication-production:
  #   container_name: authentication-production
  #   build:
  #     target: production
  #     context: .
  #     args:
  #       - PORT=${PORT:-3000}
  #   ports:
  #     - "${PORT:-3000}:${PORT:-3000}"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: "512m"
  #       reservations:
  #         cpus: "0.25"
  #         memory: "256m"

  auth-dev:
    depends_on:
      - nats-server
    container_name: auth-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
      - '9229:9229'
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          cpus: '0.25'
          memory: '256m'

  auth-db:
    container_name: auth-db
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
