services:
  nats-server:
    image: nats:latest
    ports:
      - 4222:4222

  authentication:
    depends_on:
      - nats-server
    container_name: authentication
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
      - '9229:9229'
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          cpus: '0.25'
          memory: '256m'

  authentication-database:
    container_name: authentication-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${PORT_DB:-5432}:${PORT_DB:-5432}
    env_file: .env
